package top.auzqy.comment.dao;

import org.apache.ibatis.annotations.Param;
import top.auzqy.comment.model.UserModel;

public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 27 21:28:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 27 21:28:05 CST 2019
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 27 21:28:05 CST 2019
     */
    int insertSelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 27 21:28:05 CST 2019
     */
    UserModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 27 21:28:05 CST 2019
     */
    int updateByPrimaryKeySelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 27 21:28:05 CST 2019
     */
    int updateByPrimaryKey(UserModel record);

    /**
     * description:  依据 telephone 和 password 查询结果
     * createTime: 2019-12-28 16:19
     * @author au
     * @param telephone
     * @param password
     * @return
     */
    UserModel selectByTelephoneAndPassword(@Param("telephone") String telephone,
                                           @Param("password") String password);
}