package top.auzqy.comment.model;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class ShopModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.id
     *
     * @mbg.generated Sun Dec 29 16:24:43 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.created_at
     *
     * @mbg.generated Sun Dec 29 16:24:43 CST 2019
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.updated_at
     *
     * @mbg.generated Sun Dec 29 16:24:43 CST 2019
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.name
     *
     * @mbg.generated Sun Dec 29 16:24:43 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.remark_score
     *
     * @mbg.generated Sun Dec 29 16:24:43 CST 2019
     */
    private BigDecimal remarkScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.price_per_man
     *
     * @mbg.generated Sun Dec 29 16:24:43 CST 2019
     */
    private Integer pricePerMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.latitude
     *
     * @mbg.generated Sun Dec 29 16:24:43 CST 2019
     */
    private BigDecimal latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.longitude
     *
     * @mbg.generated Sun Dec 29 16:24:43 CST 2019
     */
    private BigDecimal longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.category_id
     *
     * @mbg.generated Sun Dec 29 16:24:43 CST 2019
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.tags
     *
     * @mbg.generated Sun Dec 29 16:24:43 CST 2019
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.start_time
     *
     * @mbg.generated Sun Dec 29 16:24:43 CST 2019
     */
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.end_time
     *
     * @mbg.generated Sun Dec 29 16:24:43 CST 2019
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.address
     *
     * @mbg.generated Sun Dec 29 16:24:43 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.seller_id
     *
     * @mbg.generated Sun Dec 29 16:24:43 CST 2019
     */
    private Integer sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.icon_url
     *
     * @mbg.generated Sun Dec 29 16:24:43 CST 2019
     */
    private String iconUrl;

    private Integer distance;
    private CategoryModel categoryModel;
    private SellerModel sellerModel;
}